<x-layouts.authenticated :title="$routineTemplate->name">
    <x-page-header :title="$routineTemplate->name" description="Plantilla reutilizable con datos copiados e independientes de la biblioteca de ejercicios."><x-slot:actions><a href="{{ route('routine-templates.edit', $routineTemplate) }}" class="inline-flex min-h-11 items-center rounded-xl bg-brand-600 px-5 text-sm font-semibold text-white">Editar plantilla</a></x-slot:actions></x-page-header>
    <div class="mt-8 grid gap-6 lg:grid-cols-[minmax(0,1fr)_20rem]">
        <section class="space-y-4" aria-labelledby="composition-title"><h2 id="composition-title" class="text-xl font-semibold">Ejercicios en orden</h2>
            @forelse($routineTemplate->exercises as $item)
                <article class="min-w-0 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div class="flex gap-3"><span class="flex size-8 shrink-0 items-center justify-center rounded-full bg-brand-50 font-semibold text-brand-800">{{ $item->position }}</span><div class="min-w-0"><h3 class="break-words font-semibold text-slate-950">{{ $item->name }}</h3><p class="mt-2 whitespace-pre-line break-words text-sm leading-6 text-slate-600">{{ $item->description ?: 'Sin descripción configurada.' }}</p></div></div><dl class="mt-5 grid grid-cols-3 gap-2 text-center text-sm"><div class="rounded-xl bg-slate-50 p-2"><dt class="text-xs text-slate-500">Duración</dt><dd class="mt-1 font-semibold">{{ $item->formatted_duration }}</dd></div><div class="rounded-xl bg-slate-50 p-2"><dt class="text-xs text-slate-500">Sets</dt><dd class="mt-1 font-semibold">{{ $item->sets ?? '—' }}</dd></div><div class="rounded-xl bg-slate-50 p-2"><dt class="text-xs text-slate-500">Repet.</dt><dd class="mt-1 font-semibold">{{ $item->repetitions ?? '—' }}</dd></div></dl>@if($item->material_url)<a href="{{ $item->material_url }}" target="_blank" rel="noopener noreferrer" class="mt-4 inline-flex min-h-11 max-w-full items-center break-all font-semibold text-brand-700">Abrir material externo</a>@endif</article>
            @empty <x-card><x-empty-state title="Plantilla sin ejercicios" description="Puedes guardarla así y agregar ejercicios desde la edición antes de utilizarla en un plan." /></x-card> @endforelse
        </section>
        <aside class="space-y-4"><x-card class="p-5"><h2 class="font-semibold">Acerca de esta copia</h2><p class="mt-2 text-sm leading-6 text-slate-600">Editar o archivar los ejercicios originales no cambia esta composición.</p></x-card><x-card class="p-5"><h2 class="font-semibold text-red-800">Archivar plantilla</h2><p class="mt-2 text-sm leading-6 text-slate-600">Dejará de estar disponible para nuevos planes. Las copias que se creen en planes serán independientes y las ya utilizadas no se verán afectadas.</p><form method="POST" action="{{ route('routine-templates.destroy', $routineTemplate) }}" class="mt-4" x-data="{confirmed:false,submitting:false}" x-on:submit="submitting=true">@csrf @method('DELETE')<label class="flex gap-3 text-sm"><input type="checkbox" name="archive_confirmed" value="1" required x-model="confirmed" class="mt-0.5 size-4"><span>Confirmo que deseo archivar esta plantilla.</span></label>@error('archive_confirmed')<p class="mt-2 text-sm text-red-700">{{ $message }}</p>@enderror<button :disabled="!confirmed || submitting" class="mt-4 min-h-11 w-full rounded-xl bg-red-700 px-4 text-sm font-semibold text-white disabled:opacity-50">Archivar plantilla</button></form></x-card><a href="{{ route('routine-templates.index') }}" class="inline-flex min-h-11 w-full items-center justify-center rounded-xl px-4 text-sm font-semibold text-slate-600">Volver a la biblioteca</a></aside>
    </div>
</x-layouts.authenticated>
