@php
$editing=isset($routine);
$stored=$editing?$routine->exercises->map(fn($x)=>$x->only(['id','source_exercise_id','position','name','description','duration_seconds','sets','repetitions','material_url']))->values()->all():[];
$initial=old('exercises',$stored);
$initial=is_array($initial)?$initial:[];
@endphp
@if($errors->any())<x-alert type="error" class="mb-6">No se guardó la rutina. Revisa fechas, composición y orden.</x-alert>@endif
@php($operationErrors = collect(['routine','plan'])->flatMap(fn($key) => $errors->get($key))->values())
@if($operationErrors->isNotEmpty())
    <x-alert type="error" class="mb-6"><ul class="list-disc space-y-1 pl-5">
        @foreach($operationErrors as $message)<li>{{ $message }}</li>@endforeach
    </ul></x-alert>
@endif
<form method="POST" action="{{ $editing?route('plans.routines.update',[$plan,$routine]):route('plans.routines.store',$plan) }}" x-data="routineTemplateEditor(@js(route('routine-templates.exercise-search')),@js($initial))" x-init="init" x-on:submit="prepareSubmit" class="space-y-6">@csrf @if($editing)@method('PUT')<input type="hidden" name="updated_at" value="{{ old('updated_at',$routine->updated_at->toISOString()) }}">@endif
<input type="hidden" name="exercises" value="">
<x-card class="grid gap-5 p-5 sm:grid-cols-2 sm:p-6"><div class="sm:col-span-2"><label for="name" class="block text-sm font-semibold">Nombre</label><input id="name" name="name" required maxlength="160" value="{{ old('name',$routine->name??'') }}" class="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3">@error('name')<p class="mt-2 text-sm text-red-700">{{ $message }}</p>@enderror</div><div><label for="starts_on" class="block text-sm font-semibold">Inicio</label><input id="starts_on" name="starts_on" type="date" min="{{ $plan->starts_on->format('Y-m-d') }}" max="{{ $plan->ends_on->format('Y-m-d') }}" required value="{{ old('starts_on',isset($routine)?$routine->starts_on->format('Y-m-d'):$plan->starts_on->format('Y-m-d')) }}" class="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3"></div><div><label for="ends_on" class="block text-sm font-semibold">Fin</label><input id="ends_on" name="ends_on" type="date" min="{{ $plan->starts_on->format('Y-m-d') }}" max="{{ $plan->ends_on->format('Y-m-d') }}" required value="{{ old('ends_on',isset($routine)?$routine->ends_on->format('Y-m-d'):$plan->ends_on->format('Y-m-d')) }}" class="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3"></div>@error('starts_on')<p class="sm:col-span-2 text-sm text-red-700">{{ $message }}</p>@enderror</x-card>
<x-card><div class="border-b border-slate-200 p-5 sm:p-6"><h2 class="font-semibold">Agregar desde la biblioteca</h2><div class="mt-4 flex gap-2"><label for="exercise-search" class="sr-only">Buscar ejercicio</label><input id="exercise-search" type="search" x-model="query" x-on:input.debounce.300ms="search" placeholder="Buscar ejercicio" class="min-h-11 min-w-0 flex-1 rounded-xl border border-slate-300 px-3"><button type="button" x-on:click="search" class="rounded-xl bg-slate-900 px-4 text-sm font-semibold text-white">Buscar</button></div><p x-show="loading" class="mt-3 text-sm text-slate-500">Buscando…</p><ul class="mt-3 grid gap-2 sm:grid-cols-2"><template x-for="result in results" :key="result.id"><li class="flex items-center justify-between gap-2 rounded-xl border border-slate-200 p-3"><span class="min-w-0 truncate text-sm font-semibold" x-text="result.name"></span><button type="button" x-on:click="add(result)" class="min-h-11 rounded-xl bg-brand-50 px-3 text-sm font-semibold text-brand-800">Agregar</button></li></template></ul></div>
@error('exercises')<p class="m-5 rounded-xl bg-red-50 p-3 text-sm text-red-800">{{ $message }}</p>@enderror
<div x-show="items.length===0" class="p-8 text-center text-sm text-slate-600">Puedes guardar la rutina vacía mientras el plan esté en pausa, pero no activarlo.</div><div class="divide-y divide-slate-200"><template x-for="(item,index) in items" :key="item.key"><fieldset class="p-5 sm:p-6"><legend class="sr-only" x-text="`Ejercicio ${index+1}`"></legend><input type="hidden" :name="`exercises[${index}][id]`" :value="item.id||''"><input type="hidden" :name="`exercises[${index}][source_exercise_id]`" :value="item.source_exercise_id||''"><input type="hidden" :name="`exercises[${index}][position]`" :value="index+1"><div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><h3 class="font-semibold"><span x-text="`${index+1}. ${item.name}`"></span></h3><div class="flex flex-wrap gap-2"><button type="button" x-on:click="move(index,-1)" :disabled="index===0" class="min-h-11 rounded-xl border px-3 text-sm font-semibold disabled:opacity-40">Subir</button><button type="button" x-on:click="move(index,1)" :disabled="index===items.length-1" class="min-h-11 rounded-xl border px-3 text-sm font-semibold disabled:opacity-40">Bajar</button><button type="button" x-on:click="remove(index)" class="min-h-11 rounded-xl border border-red-200 px-3 text-sm font-semibold text-red-700">Retirar</button></div></div><div class="mt-4 grid gap-4 sm:grid-cols-2"><div class="sm:col-span-2"><label :for="`copy-name-${item.key}`" class="block text-sm font-semibold">Nombre copiado</label><input :id="`copy-name-${item.key}`" :name="`exercises[${index}][name]`" x-model="item.name" required maxlength="160" class="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3"></div><div class="sm:col-span-2"><label class="block text-sm font-semibold">Descripción</label><textarea :name="`exercises[${index}][description]`" x-model="item.description" rows="2" class="mt-2 w-full rounded-xl border border-slate-300 px-3"></textarea></div><div><label class="block text-sm font-semibold">Duración (segundos)</label><input :name="`exercises[${index}][duration_seconds]`" x-model="item.duration_seconds" type="number" min="1" class="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3"></div><div><label class="block text-sm font-semibold">Sets</label><input :name="`exercises[${index}][sets]`" x-model="item.sets" type="number" min="1" class="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3"></div><div><label class="block text-sm font-semibold">Repeticiones</label><input :name="`exercises[${index}][repetitions]`" x-model="item.repetitions" type="number" min="1" class="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3"></div><div class="sm:col-span-2"><label class="block text-sm font-semibold">URL del material</label><input :name="`exercises[${index}][material_url]`" x-model="item.material_url" type="url" class="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3"></div></div></fieldset></template></div></x-card>
<div class="flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><a href="{{ route('plans.show',$plan) }}" class="inline-flex min-h-11 items-center justify-center px-5">Cancelar</a><button x-bind:disabled="submitting" class="min-h-11 rounded-xl bg-brand-600 px-5 text-sm font-semibold text-white disabled:opacity-60">Guardar rutina</button></div></form>
