@php($editing = isset($plan))
@if($errors->any())<x-alert type="error" class="mb-6">No pudimos guardar el plan. Revisa los campos indicados.</x-alert>@endif
<form method="POST" action="{{ $editing ? route('plans.update', $plan) : route('plans.store') }}" class="space-y-6">
    @csrf @if($editing) @method('PUT') <input type="hidden" name="updated_at" value="{{ old('updated_at', $plan->updated_at->toISOString()) }}"> @endif
    <x-card class="p-5 sm:p-6"><div class="grid gap-5 sm:grid-cols-2">
        @if(!$editing)<div class="sm:col-span-2"><label for="patient_id" class="block text-sm font-semibold">Paciente</label><select id="patient_id" name="patient_id" required class="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3"><option value="">Selecciona un paciente activo</option>@foreach($patients as $patientOption)<option value="{{ $patientOption->id }}" @selected((string)old('patient_id', $selectedPatient?->id) === (string)$patientOption->id)>{{ $patientOption->full_name }}</option>@endforeach</select>@error('patient_id')<p class="mt-2 text-sm text-red-700">{{ $message }}</p>@enderror</div>@endif
        <div class="sm:col-span-2"><label for="name" class="block text-sm font-semibold">Nombre del plan</label><input id="name" name="name" required maxlength="160" value="{{ old('name', $plan->name ?? '') }}" class="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3">@error('name')<p class="mt-2 text-sm text-red-700">{{ $message }}</p>@enderror</div>
        <div><label for="starts_on" class="block text-sm font-semibold">Fecha inicial</label><input id="starts_on" name="starts_on" type="date" required value="{{ old('starts_on', isset($plan) ? $plan->starts_on->format('Y-m-d') : '') }}" class="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3">@error('starts_on')<p class="mt-2 text-sm text-red-700">{{ $message }}</p>@enderror</div>
        <div><label for="ends_on" class="block text-sm font-semibold">Fecha final</label><input id="ends_on" name="ends_on" type="date" required value="{{ old('ends_on', isset($plan) ? $plan->ends_on->format('Y-m-d') : '') }}" class="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3">@error('ends_on')<p class="mt-2 text-sm text-red-700">{{ $message }}</p>@enderror</div>
    </div><p class="mt-5 text-sm text-slate-600">El plan se guarda en pausa. Podrás activarlo cuando sus rutinas cubran todo el rango y cada una tenga ejercicios.</p></x-card>
    <div class="flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><a href="{{ $editing ? route('plans.show',$plan) : route('plans.index') }}" class="inline-flex min-h-11 items-center justify-center rounded-xl border border-slate-300 px-5 text-sm font-semibold">Cancelar</a><button class="min-h-11 rounded-xl bg-brand-600 px-5 text-sm font-semibold text-white">{{ $editing ? 'Guardar cambios' : 'Crear plan en pausa' }}</button></div>
</form>
