<x-layouts.authenticated :title="$plan->name">
<x-page-header :title="$plan->name" :description="$plan->patient->full_name.' · '.$plan->starts_on->format('d/m/Y').' – '.$plan->ends_on->format('d/m/Y')"><x-slot:actions><div class="flex flex-wrap gap-2"><a href="{{ route('plans.edit',$plan) }}" class="inline-flex min-h-11 items-center rounded-xl border border-slate-300 px-4 text-sm font-semibold">Editar datos</a><a href="{{ route('plans.duplicate-form',$plan) }}" class="inline-flex min-h-11 items-center rounded-xl bg-slate-900 px-4 text-sm font-semibold text-white">Duplicar</a></div></x-slot:actions></x-page-header>
@php($operationErrors = collect(['status','routine','plan'])->flatMap(fn($key) => $errors->get($key))->values())
@if($operationErrors->isNotEmpty())
    <x-alert type="error" class="mt-5"><ul class="list-disc space-y-1 pl-5">
        @foreach($operationErrors as $message)<li>{{ $message }}</li>@endforeach
    </ul></x-alert>
@endif
<div class="mt-8 grid gap-6 lg:grid-cols-[minmax(0,1fr)_22rem]"><div class="space-y-6">
<x-card><div class="flex flex-col gap-4 border-b border-slate-200 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="text-lg font-semibold">Rutinas del plan</h2><p class="mt-1 text-sm text-slate-600">Las fechas son inclusivas y se evalúan en America/Lima.</p></div>@if($plan->status!=='finished')<div class="flex flex-wrap gap-2"><a href="{{ route('plans.routines.copy-form',$plan) }}" class="inline-flex min-h-11 items-center rounded-xl border border-brand-300 px-4 text-sm font-semibold text-brand-800">Copiar plantilla</a><a href="{{ route('plans.routines.create',$plan) }}" class="inline-flex min-h-11 items-center rounded-xl bg-brand-600 px-4 text-sm font-semibold text-white">Agregar rutina</a></div>@endif</div>
<div class="divide-y divide-slate-200">@forelse($plan->routines as $routine)<article class="p-5 sm:p-6"><div class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h3 class="font-semibold">{{ $routine->name }}</h3><p class="mt-1 text-sm text-slate-600">{{ $routine->starts_on->format('d/m/Y') }} – {{ $routine->ends_on->format('d/m/Y') }} · {{ $routine->exercises->count() }} ejercicio(s) @if($currentRoutine?->id===$routine->id)<span class="ml-1 rounded-full bg-emerald-100 px-2 py-1 text-xs font-semibold text-emerald-800">Vigente hoy</span>@endif</p></div>@if($plan->status!=='finished')<div class="flex gap-2"><a href="{{ route('plans.routines.edit',[$plan,$routine]) }}" class="inline-flex min-h-11 items-center rounded-xl border border-slate-300 px-3 text-sm font-semibold">Editar</a><form method="POST" action="{{ route('plans.routines.destroy',[$plan,$routine]) }}">@csrf @method('DELETE')<button class="min-h-11 rounded-xl border border-red-200 px-3 text-sm font-semibold text-red-700" onclick="return confirm('¿Retirar esta rutina del plan?')">Retirar</button></form></div>@endif</div>
<ol class="mt-4 space-y-2">@foreach($routine->exercises as $exercise)<li class="flex gap-3 rounded-xl bg-slate-50 p-3 text-sm"><span class="font-semibold text-brand-700">{{ $exercise->position }}.</span><span>{{ $exercise->name }} <span class="text-slate-500">· {{ $exercise->sets ?? '—' }} sets · {{ $exercise->repetitions ?? '—' }} rep.</span></span></li>@endforeach</ol></article>@empty<div class="p-6"><x-empty-state title="Plan sin rutinas" description="Agrega una rutina manualmente o copia una plantilla para comenzar."/></div>@endforelse</div></x-card>
</div><aside class="space-y-5">
<x-card class="p-5"><h2 class="font-semibold">Estado del plan</h2><span class="mt-3 inline-flex rounded-full px-3 py-1 text-sm font-semibold {{ $plan->status==='active'?'bg-emerald-100 text-emerald-800':($plan->status==='finished'?'bg-slate-200 text-slate-700':'bg-amber-100 text-amber-900') }}">{{ ['active'=>'Activo','paused'=>'En pausa','finished'=>'Finalizado'][$plan->status] }}</span>@if($plan->status!=='finished')<div class="mt-5 space-y-3">@if($plan->status==='paused')<form method="POST" action="{{ route('plans.status',$plan) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="active"><button class="min-h-11 w-full rounded-xl bg-emerald-700 px-4 text-sm font-semibold text-white">Activar plan</button></form>@else<form method="POST" action="{{ route('plans.status',$plan) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="paused"><button class="min-h-11 w-full rounded-xl border border-slate-300 px-4 text-sm font-semibold">Pausar plan</button></form>@endif<form method="POST" action="{{ route('plans.status',$plan) }}" onsubmit="return confirm('Finalizar es irreversible. ¿Deseas continuar?')">@csrf @method('PATCH')<input type="hidden" name="status" value="finished"><button class="min-h-11 w-full rounded-xl border border-red-300 px-4 text-sm font-semibold text-red-800">Finalizar plan</button></form></div>@endif</x-card>
<x-card class="p-5"><h2 class="font-semibold">Preparación para activar</h2>@if($problems===[])<p class="mt-2 text-sm leading-6 text-emerald-800">La configuración está completa. Puede activarse.</p>@else<ul class="mt-3 list-disc space-y-2 pl-5 text-sm text-amber-900">@foreach($problems as $problem)<li>{{ $problem }}</li>@endforeach</ul>@endif</x-card>
<x-card class="p-5"><h2 class="font-semibold">Enlace seguro</h2><p class="mt-2 text-sm leading-6 text-slate-600">{{ $plan->currentPublicLink ? 'Enlace preparado. Referencia técnica: '.$plan->currentPublicLink->token_prefix.'…' : 'Se generará automáticamente en la primera activación válida.' }}</p></x-card>
<a href="{{ route('patients.show',$plan->patient) }}" class="inline-flex min-h-11 w-full items-center justify-center rounded-xl text-sm font-semibold text-slate-600">Ver paciente</a></aside></div>
</x-layouts.authenticated>
